// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGatewayApp = "gateway_app"

// GatewayApp mapped from table <gateway_app>
type GatewayApp struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 自增id
	AppID    string    `gorm:"column:app_id;not null" json:"app_id"`              // 租户id
	Name     string    `gorm:"column:name;not null" json:"name"`                  // 租户名称
	Secret   string    `gorm:"column:secret;not null" json:"secret"`              // 密钥
	WhiteIps string    `gorm:"column:white_ips;not null" json:"white_ips"`        // ip白名单，支持前缀匹配
	Qpd      int64     `gorm:"column:qpd;not null" json:"qpd"`                    // 日请求量限制
	QPS      int64     `gorm:"column:qps;not null" json:"qps"`                    // 每秒请求量限制
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`        // 添加时间
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`        // 更新时间
	IsDelete int8      `gorm:"column:is_delete;not null" json:"is_delete"`        // 是否删除 1=删除
}

// TableName GatewayApp's table name
func (*GatewayApp) TableName() string {
	return TableNameGatewayApp
}
