// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGatewayServiceHTTPRule = "gateway_service_http_rule"

// GatewayServiceHTTPRule mapped from table <gateway_service_http_rule>
type GatewayServiceHTTPRule struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`      // 自增主键
	ServiceID      int64  `gorm:"column:service_id;not null" json:"service_id"`           // 服务id
	RuleType       int8   `gorm:"column:rule_type;not null" json:"rule_type"`             // 匹配类型 0=url前缀url_prefix 1=域名domain
	Rule           string `gorm:"column:rule;not null" json:"rule"`                       // type=domain表示域名，type=url_prefix时表示url前缀
	NeedHTTPS      int8   `gorm:"column:need_https;not null" json:"need_https"`           // 支持https 1=支持
	NeedStripURI   int8   `gorm:"column:need_strip_uri;not null" json:"need_strip_uri"`   // 启用strip_uri 1=启用
	NeedWebsocket  int8   `gorm:"column:need_websocket;not null" json:"need_websocket"`   // 是否支持websocket 1=支持
	URLRewrite     string `gorm:"column:url_rewrite;not null" json:"url_rewrite"`         // url重写功能 格式：^/gatekeeper/test_service(.*) $1 多个逗号间隔
	HeaderTransfor string `gorm:"column:header_transfor;not null" json:"header_transfor"` // header转换支持增加(add)、删除(del)、修改(edit) 格式: add headname headvalue 多个逗号间隔
}

// TableName GatewayServiceHTTPRule's table name
func (*GatewayServiceHTTPRule) TableName() string {
	return TableNameGatewayServiceHTTPRule
}
