// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGatewayServiceGrpcRule = "gateway_service_grpc_rule"

// GatewayServiceGrpcRule mapped from table <gateway_service_grpc_rule>
type GatewayServiceGrpcRule struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`      // 自增主键
	ServiceID      int64  `gorm:"column:service_id;not null" json:"service_id"`           // 服务id
	Port           int64  `gorm:"column:port;not null" json:"port"`                       // 端口
	HeaderTransfor string `gorm:"column:header_transfor;not null" json:"header_transfor"` // header转换支持增加(add)、删除(del)、修改(edit) 格式: add headname headvalue 多个逗号间隔
}

// TableName GatewayServiceGrpcRule's table name
func (*GatewayServiceGrpcRule) TableName() string {
	return TableNameGatewayServiceGrpcRule
}
