// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGatewayServiceInfo = "gateway_service_info"

// GatewayServiceInfo mapped from table <gateway_service_info>
type GatewayServiceInfo struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 自增主键
	LoadType    int8      `gorm:"column:load_type;not null" json:"load_type"`                               // 负载类型 0=http 1=tcp 2=grpc
	ServiceName string    `gorm:"column:service_name;not null" json:"service_name"`                         // 服务名称 6-128 数字字母下划线
	ServiceDesc string    `gorm:"column:service_desc;not null" json:"service_desc"`                         // 服务描述
	CreateAt    time.Time `gorm:"column:create_at;not null;default:'1971-01-01 00:00:00'" json:"create_at"` // 添加时间
	UpdateAt    time.Time `gorm:"column:update_at;not null;default:'1971-01-01 00:00:00'" json:"update_at"` // 更新时间
	IsDelete    int8      `gorm:"column:is_delete" json:"is_delete"`                                        // 是否删除 1=删除
}

// TableName GatewayServiceInfo's table name
func (*GatewayServiceInfo) TableName() string {
	return TableNameGatewayServiceInfo
}
