// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGatewayServiceTcpRule = "gateway_service_tcp_rule"

// GatewayServiceTcpRule mapped from table <gateway_service_tcp_rule>
type GatewayServiceTcpRule struct {
	ID        int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 自增主键
	ServiceID int64 `gorm:"column:service_id;not null" json:"service_id"`      // 服务id
	Port      int64 `gorm:"column:port;not null" json:"port"`                  // 端口号
}

// TableName GatewayServiceTcpRule's table name
func (*GatewayServiceTcpRule) TableName() string {
	return TableNameGatewayServiceTcpRule
}
