// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGatewayServiceAccessControl = "gateway_service_access_control"

// GatewayServiceAccessControl mapped from table <gateway_service_access_control>
type GatewayServiceAccessControl struct {
	ID                int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`              // 自增主键
	ServiceID         int64  `gorm:"column:service_id;not null" json:"service_id"`                   // 服务id
	OpenAuth          int8   `gorm:"column:open_auth;not null" json:"open_auth"`                     // 是否开启权限 1=开启
	BlackList         string `gorm:"column:black_list;not null" json:"black_list"`                   // 黑名单ip
	WhiteList         string `gorm:"column:white_list;not null" json:"white_list"`                   // 白名单ip
	WhiteHostName     string `gorm:"column:white_host_name;not null" json:"white_host_name"`         // 白名单主机
	ClientipFlowLimit int64  `gorm:"column:clientip_flow_limit;not null" json:"clientip_flow_limit"` // 客户端ip限流
	ServiceFlowLimit  int64  `gorm:"column:service_flow_limit;not null" json:"service_flow_limit"`   // 服务端限流
}

// TableName GatewayServiceAccessControl's table name
func (*GatewayServiceAccessControl) TableName() string {
	return TableNameGatewayServiceAccessControl
}
