// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameGatewayAdmin = "gateway_admin"

// GatewayAdmin mapped from table <gateway_admin>
type GatewayAdmin struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 自增id
	UserName   string         `gorm:"column:user_name;not null" json:"user_name"`        // 用户名
	Salt       string         `gorm:"column:salt;not null" json:"salt"`                  // 盐
	Password   string         `gorm:"column:password;not null" json:"password"`          // 密码
	CreateTime int64          `gorm:"column:create_time;not null" json:"create_time"`    // 新增时间
	UpdateTime int64          `gorm:"column:update_time;not null" json:"update_time"`    // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 是否删除
}

// TableName GatewayAdmin's table name
func (*GatewayAdmin) TableName() string {
	return TableNameGatewayAdmin
}
