// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGatewayServiceLoadBalance = "gateway_service_load_balance"

// GatewayServiceLoadBalance mapped from table <gateway_service_load_balance>
type GatewayServiceLoadBalance struct {
	ID                     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 自增主键
	ServiceID              int64  `gorm:"column:service_id;not null" json:"service_id"`                             // 服务id
	CheckMethod            int8   `gorm:"column:check_method;not null" json:"check_method"`                         // 检查方法 0=tcpchk,检测端口是否握手成功
	CheckTimeout           int64  `gorm:"column:check_timeout;not null" json:"check_timeout"`                       // check超时时间,单位s
	CheckInterval          int64  `gorm:"column:check_interval;not null" json:"check_interval"`                     // 检查间隔, 单位s
	RoundType              int8   `gorm:"column:round_type;not null;default:2" json:"round_type"`                   // 轮询方式 0=random 1=round-robin 2=weight_round-robin 3=ip_hash
	IPList                 string `gorm:"column:ip_list;not null" json:"ip_list"`                                   // ip列表
	WeightList             string `gorm:"column:weight_list;not null" json:"weight_list"`                           // 权重列表
	ForbidList             string `gorm:"column:forbid_list;not null" json:"forbid_list"`                           // 禁用ip列表
	UpstreamConnectTimeout int64  `gorm:"column:upstream_connect_timeout;not null" json:"upstream_connect_timeout"` // 建立连接超时, 单位s
	UpstreamHeaderTimeout  int64  `gorm:"column:upstream_header_timeout;not null" json:"upstream_header_timeout"`   // 获取header超时, 单位s
	UpstreamIdleTimeout    int64  `gorm:"column:upstream_idle_timeout;not null" json:"upstream_idle_timeout"`       // 链接最大空闲时间, 单位s
	UpstreamMaxIdle        int64  `gorm:"column:upstream_max_idle;not null" json:"upstream_max_idle"`               // 最大空闲链接数
}

// TableName GatewayServiceLoadBalance's table name
func (*GatewayServiceLoadBalance) TableName() string {
	return TableNameGatewayServiceLoadBalance
}
